// Generated by scripts/process-frames.mjs — do not edit by hand.
// Run `bun run frames` after changing anything in assets/frames-src/.

export const FRAME_COUNT = 241;

export const FRAME_TIERS = {
  desktop: { width: 1600, height: 900 },
  mobile: { width: 960, height: 540 },
  portrait: { width: 540, height: 960 },
} as const;

export type FrameTier = keyof typeof FRAME_TIERS;

/** Blurred frame 1, inlined as the pre-load poster. */
export const FRAME_LQIP =
  "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAAAQBgCdASogABIAPsFSokqnpKMhsAgA8BgJZACdMtVCv6mDp2754OUbmW1asPZgcaEJC19+MJxH6BAA/IaWh+ehhS76GswfJgUtFHVZi0MfqyEPH1sobrExHzis+QDPY+MIA+8+pI2WihMmsLQyFLxfIFEUWZ9twND7TN7nxlEtN1bAyBh11fEFSXGE51ufaYhaAXztr+hHrM8wdc92l5zlGLMOTPTxQ4QLRChYAAA=";

/**
 * Frame 1, pre-graded to brightness 0.55 / saturation 1.45, for the
 * intro heading's mask. Baked rather than filtered at runtime — see the
 * note in scripts/process-frames.mjs.
 */
export const FRAME_MASK_FILL = "/frames/mask-fill.webp";

export function frameSrc(tier: FrameTier, index: number): string {
  return `/frames/${tier}/f-${String(index + 1).padStart(3, "0")}.webp`;
}
