// Generated by scripts/process-frames.mjs — do not edit by hand.
// Run `bun run frames` after changing anything in assets/frames-src/.

export const FRAME_COUNT = 199;

export const FRAME_TIERS = {
  desktop: { width: 1600, height: 900 },
  mobile: { width: 960, height: 540 },
} as const;

export type FrameTier = keyof typeof FRAME_TIERS;

/** Blurred frame 1, inlined as the pre-load poster. */
export const FRAME_LQIP =
  "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAABwBQCdASogABIAPsFSokqnpKMhsAgA8BgJZgCdMuI3WDGujIEnEUWi5+jGwg49KgBGtf34AP5VZt2nI2G+n6Rln/MQsqzmcz5llZnQLMbAF0BTmdWPtI3ls/txplkclmKRTR3H5AdGwcH+2nkYUuXexoOJHA9K8BQua1npU5R6D3v4ckhK3t0iNeCgm0DhKOkwNLaT1HkkKYrltS/HYFzlUZZ9kPDEjr0AAA==";

/**
 * Frame 1, pre-graded to brightness 0.55 / saturation 1.45, for the
 * intro heading's mask. Baked rather than filtered at runtime — see the
 * note in scripts/process-frames.mjs.
 */
export const FRAME_MASK_FILL = "/frames/mask-fill.webp";

export function frameSrc(tier: FrameTier, index: number): string {
  return `/frames/${tier}/f-${String(index + 1).padStart(3, "0")}.webp`;
}
