// Generated by scripts/process-frames.mjs — do not edit by hand.
// Run `bun run frames` after changing anything in assets/frames-src/.

export const FRAME_COUNT = 241;

export const FRAME_TIERS = {
  desktop: { width: 1600, height: 900 },
  mobile: { width: 960, height: 540 },
  portrait: { width: 540, height: 960 },
} as const;

export type FrameTier = keyof typeof FRAME_TIERS;

/** Blurred frame 1, inlined as the pre-load poster. */
export const FRAME_LQIP =
  "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAADwBQCdASogABIAPsFWokunpSMhsBgIAPAYCWQAnTLjf3gWAdO3QZnJbqxaPzz+bvszXhx6aLYWoAD8hpaH6Y5NJS/2u9froP2BidMvi7heWprX9OHCVBNAdWabbX1qvRaVLzRZzj5mBeZp0+OWm1D/t5x6Qf/xx/5qIqHIkmdz/4jirRDBCqtqyAAH2ve2r9EcSOGNpfzJKF88z/9vrVeGXBS6FkcksUlE08vNsX1AAA==";

/**
 * Frame 1, pre-graded to brightness 0.55 / saturation 1.45, for the
 * intro heading's mask. Baked rather than filtered at runtime — see the
 * note in scripts/process-frames.mjs.
 */
export const FRAME_MASK_FILL = "/frames/mask-fill.webp";

/** The same still, cut to the portrait tier for phones. */
export const FRAME_MASK_FILL_PORTRAIT = "/frames/mask-fill-portrait.webp";

export function frameSrc(tier: FrameTier, index: number): string {
  return `/frames/${tier}/f-${String(index + 1).padStart(3, "0")}.webp`;
}
