#!/usr/bin/env node
/**
 * Downscales the 4K source frames into the WebP tiers the canvas scrubber
 * consumes, and emits a manifest module for the app to import.
 *
 * The sources stay out of `public/` on purpose: a 3840x2160 frame decodes to
 * ~33MB of bitmap, so handing all 199 to the browser would need ~6.6GB. The
 * tiers below keep the whole sequence under 7MB on the wire instead.
 *
 *   node scripts/process-frames.mjs
 */
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC_DIR = path.join(ROOT, "assets/frames-src");
const OUT_DIR = path.join(ROOT, "public/frames");
const MANIFEST = path.join(ROOT, "src/lib/frames.generated.ts");

/** Widths are 16:9 exact against the 3840x2160 source. */
const TIERS = [
  { name: "desktop", width: 1600, height: 900 },
  { name: "mobile", width: 960, height: 540 },
];
const QUALITY = 78;
const CONCURRENCY = 8;

/**
 * The grade applied to the still that fills the intro's masked heading. Under
 * 1 for brightness and over 1 for saturation: the footage is shot on cream, so
 * ungraded the letters would read barely darker than the page behind them.
 */
const MASK_FILL = {
  brightness: 0.55,
  file: "mask-fill.webp",
  saturation: 1.45,
};

/** Runs `task` over `items`, at most `limit` in flight. */
async function pool(items, limit, task) {
  let cursor = 0;
  const workers = Array.from(
    { length: Math.min(limit, items.length) },
    async () => {
      while (cursor < items.length) {
        const index = cursor++;
        await task(items[index], index);
      }
    },
  );
  await Promise.all(workers);
}

function frameFileName(index) {
  return `f-${String(index + 1).padStart(3, "0")}.webp`;
}

async function main() {
  const sources = (await readdir(SRC_DIR))
    .filter((name) => /\.(jpe?g|png)$/i.test(name))
    .sort();

  if (sources.length === 0) {
    throw new Error(
      `No source frames found in ${path.relative(ROOT, SRC_DIR)}`,
    );
  }

  await rm(OUT_DIR, { recursive: true, force: true });

  const bytesPerTier = new Map(TIERS.map((tier) => [tier.name, 0]));

  for (const tier of TIERS) {
    await mkdir(path.join(OUT_DIR, tier.name), { recursive: true });

    await pool(sources, CONCURRENCY, async (source, index) => {
      const info = await sharp(path.join(SRC_DIR, source))
        .resize(tier.width, tier.height, { fit: "cover" })
        .webp({ quality: QUALITY, effort: 5, smartSubsample: true })
        .toFile(path.join(OUT_DIR, tier.name, frameFileName(index)));

      bytesPerTier.set(tier.name, bytesPerTier.get(tier.name) + info.size);
    });

    const total = bytesPerTier.get(tier.name);
    console.log(
      `${tier.name.padEnd(7)} ${tier.width}x${tier.height}  ` +
        `${sources.length} frames  ` +
        `${(total / sources.length / 1024).toFixed(1)} KB/frame  ` +
        `${(total / 1024 / 1024).toFixed(1)} MB total`,
    );
  }

  // A blurred first frame, inlined as the poster so the hero paints before any
  // of the sequence has landed.
  const lqip = await sharp(path.join(SRC_DIR, sources[0]))
    .resize(32)
    .blur(1.2)
    .webp({ quality: 55 })
    .toBuffer();

  // The opening frame, graded down and pushed, for use as the fill inside the
  // intro's masked heading. Baked here rather than done with a CSS `filter` at
  // runtime because that layer is deliberately not composited (see
  // MaskedHeading), so it repaints every frame — and a filter over a
  // full-bleed image is the most expensive thing in that repaint.
  const maskFill = await sharp(path.join(SRC_DIR, sources[0]))
    .resize(TIERS[0].width, TIERS[0].height, { fit: "cover" })
    .modulate({
      brightness: MASK_FILL.brightness,
      saturation: MASK_FILL.saturation,
    })
    .webp({ quality: QUALITY, effort: 5, smartSubsample: true })
    .toFile(path.join(OUT_DIR, MASK_FILL.file));

  console.log(
    `\nmask fill  ${TIERS[0].width}x${TIERS[0].height}  ` +
      `${(maskFill.size / 1024).toFixed(1)} KB`,
  );

  const tierEntries = TIERS.map(
    (tier) =>
      `  ${tier.name}: { width: ${tier.width}, height: ${tier.height} },`,
  ).join("\n");

  await mkdir(path.dirname(MANIFEST), { recursive: true });
  await writeFile(
    MANIFEST,
    `// Generated by scripts/process-frames.mjs — do not edit by hand.\n` +
      `// Run \`bun run frames\` after changing anything in assets/frames-src/.\n\n` +
      `export const FRAME_COUNT = ${sources.length};\n\n` +
      `export const FRAME_TIERS = {\n${tierEntries}\n} as const;\n\n` +
      `export type FrameTier = keyof typeof FRAME_TIERS;\n\n` +
      `/** Blurred frame 1, inlined as the pre-load poster. */\n` +
      `export const FRAME_LQIP =\n  "data:image/webp;base64,${lqip.toString("base64")}";\n\n` +
      `/**\n` +
      ` * Frame 1, pre-graded to brightness ${MASK_FILL.brightness} / saturation ${MASK_FILL.saturation}, for the\n` +
      ` * intro heading's mask. Baked rather than filtered at runtime — see the\n` +
      ` * note in scripts/process-frames.mjs.\n` +
      ` */\n` +
      `export const FRAME_MASK_FILL = "/frames/${MASK_FILL.file}";\n\n` +
      `export function frameSrc(tier: FrameTier, index: number): string {\n` +
      `  return \`/frames/\${tier}/f-\${String(index + 1).padStart(3, "0")}.webp\`;\n` +
      `}\n`,
    "utf8",
  );

  console.log(`\nmanifest -> ${path.relative(ROOT, MANIFEST)}`);
}

await main();
